name: release

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  builds:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2022]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: tree-sitter/py-tree-sitter
          ref: v0.20.0
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - if: ${{ startsWith(matrix.os, 'windows') }}
        run: cmd script\fetch-fixtures.cmd
      - if: ${{ !startsWith(matrix.os, 'windows') }}
        run: script/fetch-fixtures
      - run: pip install cibuildwheel==2.5.0
      - if: ${{ startsWith(matrix.os, 'windows') }}
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_TEST_COMMAND: dir
      - if: ${{ !startsWith(matrix.os, 'windows') }}
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_TEST_COMMAND: ls -la
      - uses: actions/upload-artifact@v2
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl
