name: release

on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2022]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: pypa/sampleproject
          ref: d424e4310bda95f5ae8cfdf1de583a973680cf88
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install cibuildwheel==2.5.0
      - run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_TEST_COMMAND: python -m unittest discover -s {project}/tests
      - uses: actions/upload-artifact@v2
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl

  release:
    runs-on: ubuntu-latest
    # https://stackoverflow.com/a/58478262
    needs: [build]
    #if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheelhouse
      - run: ls -la
#      - id: create_release
#        uses: actions/create-release@v1.1.4
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: ${{ github.ref }}
#      - uses: actions/upload-release-asset@v1.0.1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
