name: release

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  builds:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2022]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install cibuildwheel==2.5.0
      - run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_TEST_COMMAND: python -m unittest {package}/tests
      - uses: actions/upload-artifact@v2
        with:
          name: wheelhouse
          path: ./wheelhouse/*.whl
